/* ===================================================================
   ALGO HUB — Shared content data for modals
   =================================================================== */
window.ALGOHUB_MODAL_DATA = {

  /* ---------- Services ---------- */
  'saas': {
    icon: 'layout-dashboard',
    badge: 'Service',
    title: 'SaaS Product Development',
    description: 'Custom Software as a Service platforms designed for scalability, security, and business growth — from architecture to launch.',
    points: [
      'Multi-tenant architecture built for scale',
      'Secure authentication and role-based access',
      'Subscription billing and usage analytics',
      'Cloud-native deployment and monitoring',
    ],
  },
  'ai': {
    icon: 'brain-circuit',
    badge: 'Service',
    title: 'Artificial Intelligence Solutions',
    description: 'AI-powered applications, intelligent automation, predictive analytics, and recommendation systems tailored to your business.',
    points: [
      'Custom AI application development',
      'Predictive analytics and forecasting',
      'Recommendation and personalization engines',
      'End-to-end intelligent workflow automation',
    ],
  },
  'ml': {
    icon: 'network',
    badge: 'Service',
    title: 'Machine Learning Development',
    description: 'Building custom ML models for forecasting, classification, sentiment analysis, and intelligent decision-making.',
    points: [
      'Data pipeline design and feature engineering',
      'Model training, evaluation, and tuning',
      'Classification, regression, and NLP models',
      'Production deployment and monitoring',
    ],
  },
  'web': {
    icon: 'code-2',
    badge: 'Service',
    title: 'Web Development',
    description: 'Modern, responsive, high-performance websites using the latest technologies, built for speed and reliability.',
    points: [
      'Responsive, accessible interfaces',
      'Full-stack development (frontend + backend)',
      'Performance optimization and SEO fundamentals',
      'Ongoing maintenance and support',
    ],
  },
  'mobile': {
    icon: 'smartphone',
    badge: 'Service',
    title: 'Mobile App Development',
    description: 'Cross-platform Android and iOS applications with exceptional, native-quality user experiences.',
    points: [
      'Cross-platform development from a single codebase',
      'Native-feel UI and smooth interactions',
      'App store deployment support',
      'Post-launch updates and maintenance',
    ],
  },
  'uiux': {
    icon: 'pen-tool',
    badge: 'Service',
    title: 'UI/UX Design',
    description: 'Designing engaging digital experiences with user-centered interfaces that balance beauty and usability.',
    points: [
      'User research and journey mapping',
      'Wireframing and interactive prototyping',
      'Design systems and component libraries',
      'Usability testing and iteration',
    ],
  },
  'cloud': {
    icon: 'cloud',
    badge: 'Service',
    title: 'Cloud Solutions',
    description: 'Secure cloud deployment, hosting, migration, and infrastructure optimization for growing businesses.',
    points: [
      'Cloud architecture design and migration',
      'Scalable, secure hosting infrastructure',
      'Cost optimization and monitoring',
      'CI/CD pipeline setup',
    ],
  },
  'automation': {
    icon: 'workflow',
    badge: 'Service',
    title: 'Automation Solutions',
    description: 'Workflow automation, CRM integration, business process optimization, and productivity enhancement.',
    points: [
      'Custom workflow and task automation',
      'CRM and third-party tool integration',
      'Business process re-engineering',
      'Time and cost savings analysis',
    ],
  },
  'marketing': {
    icon: 'megaphone',
    badge: 'Service',
    title: 'Digital Marketing',
    description: 'SEO, Social Media Marketing, Branding, Content Marketing, and Lead Generation that drive real growth.',
    points: [
      'Search engine optimization (SEO)',
      'Social media strategy and management',
      'Brand identity and content marketing',
      'Lead generation campaigns',
    ],
  },
  'consultancy': {
    icon: 'lightbulb',
    badge: 'Service',
    title: 'Startup Consultancy',
    description: 'Helping startups validate ideas, build MVPs, scale products, and prepare for investment.',
    points: [
      'Idea validation and market research',
      'MVP strategy and roadmap planning',
      'Product-market fit guidance',
      'Investment readiness support',
    ],
  },

  /* ---------- Courses ---------- */
  'course-youtube': {
    icon: 'youtube',
    badge: '8 Weeks · Beginner',
    title: 'YouTube Automation',
    description: 'Master AI-powered content creation, monetization strategies, SEO, branding, and channel growth.',
    points: [
      'AI-assisted scripting and content creation',
      'Channel branding and audience growth',
      'YouTube SEO and algorithm fundamentals',
      'Monetization and revenue strategies',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-fiverr': {
    icon: 'briefcase',
    badge: '6 Weeks · Beginner',
    title: 'Fiverr Freelancing',
    description: 'Learn to create professional gigs, attract international clients, optimize profiles, and build a sustainable freelancing career.',
    points: [
      'Gig creation and profile optimization',
      'Client communication and proposals',
      'Pricing strategy and packages',
      'Building long-term freelance income',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-video': {
    icon: 'clapperboard',
    badge: '6 Weeks · Beginner',
    title: 'Video Editing',
    description: 'Master Adobe Premiere Pro, After Effects, CapCut, and AI-powered editing tools to create engaging content.',
    points: [
      'Premiere Pro and After Effects fundamentals',
      'Mobile editing with CapCut',
      'AI-powered editing workflows',
      'Portfolio-ready final projects',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-trading': {
    icon: 'trending-up',
    badge: '8 Weeks · Intermediate',
    title: 'Trading & Financial Markets',
    description: 'Understand market fundamentals, technical analysis, risk management, and trading psychology.',
    points: [
      'Market structure and fundamentals',
      'Technical analysis and chart reading',
      'Risk management strategies',
      'Trading psychology and discipline',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-ai': {
    icon: 'sparkles',
    badge: '10 Weeks · Intermediate',
    title: 'Artificial Intelligence',
    description: 'Learn Prompt Engineering, Generative AI, LLMs, AI Automation, ChatGPT, and intelligent workflow creation.',
    points: [
      'Prompt engineering fundamentals',
      'Working with LLMs and generative AI',
      'Building AI-powered automations',
      'Real-world AI project work',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-ml': {
    icon: 'network',
    badge: '10 Weeks · Advanced',
    title: 'Machine Learning',
    description: 'Build intelligent systems using Python, Scikit-Learn, TensorFlow, and real-world datasets.',
    points: [
      'Python for machine learning',
      'Scikit-Learn and TensorFlow',
      'Model building on real datasets',
      'Deployment-ready ML projects',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-web': {
    icon: 'code-2',
    badge: '12 Weeks · Beginner',
    title: 'Web Development',
    description: 'Learn HTML, CSS, Tailwind CSS, JavaScript, React, PHP, Laravel, Node.js, and full-stack development.',
    points: [
      'HTML, CSS, and Tailwind CSS',
      'JavaScript and React fundamentals',
      'PHP, Laravel, and Node.js backend',
      'Full-stack capstone project',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-graphic': {
    icon: 'palette',
    badge: '6 Weeks · Beginner',
    title: 'Graphic Designing',
    description: 'Create professional branding materials using Adobe Photoshop, Illustrator, Canva, and Figma.',
    points: [
      'Photoshop and Illustrator essentials',
      'Brand identity and logo design',
      'Rapid design with Canva and Figma',
      'Building a design portfolio',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },
  'course-digital-marketing': {
    icon: 'megaphone',
    badge: '8 Weeks · Beginner',
    title: 'Digital Marketing',
    description: 'SEO, Google Ads, Facebook Marketing, Email Marketing, Analytics, and Growth Strategies.',
    points: [
      'SEO and Google Ads fundamentals',
      'Facebook and social media marketing',
      'Email marketing campaigns',
      'Analytics-driven growth strategy',
    ],
    ctaHref: 'courses.html',
    ctaLabel: 'Enroll Now',
  },

  /* ---------- Projects ---------- */
  'proj-attendance': {
    icon: 'scan-face',
    badge: 'AI · Embedded Systems',
    title: 'AI Attendance System',
    description: 'A real-time face recognition attendance system built on Raspberry Pi, using deep learning embeddings for fast, accurate identification.',
    points: [
      'Deep learning-based face recognition',
      'Real-time recognition on edge hardware',
      'Admin dashboard for attendance records',
      'Role-based access for staff and students',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
  'proj-chatbot': {
    icon: 'bot',
    badge: 'AI · Automation',
    title: 'AI Chatbot',
    description: 'An intelligent conversational assistant that automates customer support and lead qualification for growing businesses.',
    points: [
      'Natural language understanding',
      'Custom knowledge base integration',
      'Multi-channel deployment',
      'Analytics on customer conversations',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
  'proj-saas-dashboard': {
    icon: 'layout-dashboard',
    badge: 'SaaS · Web App',
    title: 'SaaS Dashboard',
    description: 'A multi-tenant analytics dashboard giving businesses real-time visibility into their key performance metrics.',
    points: [
      'Real-time data visualization',
      'Role-based multi-tenant access',
      'Subscription and billing management',
      'Responsive, scalable architecture',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
  'proj-ecommerce': {
    icon: 'shopping-bag',
    badge: 'Web · E-Commerce',
    title: 'E-Commerce Website',
    description: 'A full-featured online store with secure checkout, inventory management, and a seamless shopping experience.',
    points: [
      'Product catalog and inventory management',
      'Secure payment gateway integration',
      'Order tracking and management',
      'Mobile-optimized shopping experience',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
  'proj-portfolio': {
    icon: 'user-circle',
    badge: 'Web · Personal Brand',
    title: 'Portfolio Website',
    description: 'A sleek personal portfolio designed to showcase work, skills, and experience to potential clients and employers.',
    points: [
      'Custom, distinctive visual design',
      'Project showcase with case studies',
      'Fast-loading, SEO-friendly build',
      'Fully responsive across devices',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
  'proj-hospital': {
    icon: 'heart-pulse',
    badge: 'Web · Healthcare',
    title: 'Hospital Management System',
    description: 'An end-to-end system for managing patient records, appointments, staff, and billing across a healthcare facility.',
    points: [
      'Patient records and appointment scheduling',
      'Staff and department management',
      'Billing and invoicing workflows',
      'Secure, role-based data access',
    ],
    ctaHref: 'projects.html',
    ctaLabel: 'View Similar Projects',
  },
};